-- MySQL Script generated by MySQL Workbench
-- Tue May 19 23:40:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema minimarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minimarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minimarket` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `minimarket` ;

-- -----------------------------------------------------
-- Table `minimarket`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minimarket`.`producto` (
  `sku` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `categoria` VARCHAR(100) NULL DEFAULT NULL,
  `unidad_medida` VARCHAR(30) NULL DEFAULT NULL,
  `precio_compra` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `precio_venta` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `stock_actual` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`sku`),
  INDEX `idx_producto_categoria` (`categoria` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `minimarket`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minimarket`.`proveedor` (
  `rut` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `condiciones_comerciales` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `minimarket`.`equivalencia_sku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minimarket`.`equivalencia_sku` (
  `id_equivalencia` INT NOT NULL AUTO_INCREMENT,
  `sku_interno` VARCHAR(50) NOT NULL,
  `rut_proveedor` VARCHAR(12) NOT NULL,
  `codigo_proveedor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_equivalencia`),
  UNIQUE INDEX `uq_equiv_sku_prov` (`sku_interno` ASC, `rut_proveedor` ASC) VISIBLE,
  INDEX `fk_equiv_proveedor` (`rut_proveedor` ASC) VISIBLE,
  INDEX `idx_equiv_cod_prov` (`codigo_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_equiv_producto`
    FOREIGN KEY (`sku_interno`)
    REFERENCES `minimarket`.`producto` (`sku`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_equiv_proveedor`
    FOREIGN KEY (`rut_proveedor`)
    REFERENCES `minimarket`.`proveedor` (`rut`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `minimarket`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minimarket`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `nro_factura` VARCHAR(30) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `rut_proveedor` VARCHAR(12) NOT NULL,
  `estado` ENUM('Pendiente', 'Procesada', 'Observada') NOT NULL DEFAULT 'Pendiente',
  PRIMARY KEY (`id_factura`),
  UNIQUE INDEX `uq_factura_prov` (`nro_factura` ASC, `rut_proveedor` ASC) VISIBLE,
  INDEX `idx_factura_proveedor` (`rut_proveedor` ASC) VISIBLE,
  INDEX `idx_factura_estado` (`estado` ASC) VISIBLE,
  CONSTRAINT `fk_factura_prov`
    FOREIGN KEY (`rut_proveedor`)
    REFERENCES `minimarket`.`proveedor` (`rut`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `minimarket`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minimarket`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(60) NOT NULL,
  `contrasena_hash` VARCHAR(255) NOT NULL,
  `rol` ENUM('Administrador', 'Bodeguero', 'Cajero') NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `uq_nombre_usuario` (`nombre_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `minimarket`.`mov_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minimarket`.`mov_inventario` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `id_usuario` INT NOT NULL,
  `sku` VARCHAR(50) NOT NULL,
  `stock_anterior` INT NOT NULL,
  `cantidad_aplicada` INT NOT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_movimiento`),
  INDEX `idx_mov_sku` (`sku` ASC) VISIBLE,
  INDEX `idx_mov_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_mov_fecha` (`fecha` ASC) VISIBLE,
  CONSTRAINT `fk_mov_producto`
    FOREIGN KEY (`sku`)
    REFERENCES `minimarket`.`producto` (`sku`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mov_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `minimarket`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
